name: Deploy to GitHub Pages

on:
  push:
    branches: [ fresh-start ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to docs folder
        run: |
          # Remove old docs folder
          rm -rf docs
          # Copy dist to docs
          cp -r dist docs
          # Add .nojekyll to docs
          touch docs/.nojekyll
      
      - name: Commit and push to docs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git diff --staged --quiet || git commit -m "Deploy to docs folder [skip ci]"
          git push 